[data]
target = "price_bwp"
categorical_features = [ "cut", "color", "clarity",]
numerical_features = [ "carat", "depth", "table", "volume",]

[paths]
dir = "Data"
raw_data = "diamonds.csv"
processed_data = "clean_ds.plk"
log_dir = "Logs"

[training]
random_state = 42

[autogluon]
time_limit = 600
dir = "Autogluon"

[tabnet]
max_epochs = 5
patience = 10
batch_size = 1024
virtual_batch_size = 128
dir = "Tabnet"

[optuna]
n_trials = 5
timeout = 360

[tabnet.initial_params]
n_d = 16
n_a = 32
n_steps = 8
gamma = 1.5986584841970366
lambda_sparse = 2.9380279387035354e-6

[tabnet.initial_params.optimizer_params]
lr = 0.0806234057607385
weight_decay = 1e-5

[tabnet.initial_params.scheduler_params]
patience = 10
factor = 0.5
scheduler_fn = "torch.optim.lr_scheduler.ReduceLROnPlateau"
mode = "min"
