[data]
target = "price_bwp"
cat_feats = [ "cut", "color", "clarity",]
num_feats = [ "carat", "depth", "table", "volume",]
raw = "diamonds.csv"
processed = "clean_ds.pkl"

[dir]
data = "Data"
logs = "Logs"
autogluon = "Autogluon"
tabnet = "Tabnet"

[training]
seed = 42

[autogluon]
timeout = 66600

[tabnet]
epochs = 50
patience = 10
batch_size = 1024
vbatch_size = 128

[optuna]
trials = 50
timeout = 36000

[tabnet.params]
n_d = 28
n_a = 12
n_steps = 5
gamma = 1.1242486011659727
lambda_sparse = 3.330238156087226e-5

[tabnet.params.opt_params]
lr = 0.01
weight_decay = 1e-5

[tabnet.params.sched_params]
patience = 10
factor = 0.5
scheduler_fn = "torch.optim.lr_scheduler.ReduceLROnPlateau"
mode = "min"
