[data]
target = "price"
categorical_features = [ "cut", "color", "clarity",]
numerical_features = [ "carat", "depth", "table", "volume",]

[paths]
dir = "Data"
raw_data = "diamonds.csv"
processed_data = "clean_ds.plk"
log_dir = "Logs"

[training]
random_state = 42

[autogluon]
time_limit = 60
dir = "Autogluon"

[tabnet]
max_epochs = 100
patience = 10
batch_size = 1024
virtual_batch_size = 128
dir = "Tabnet"

[optuna]
n_trials = 50
timeout = 3600

[tabnet.initial_params]
n_d = 20
n_a = 12
n_steps = 10
gamma = 1.0424030394886583
lambda_sparse = 8.850232060121019e-5

[tabnet.initial_params.optimizer_params]
lr = 0.029575984820183254
weight_decay = 1e-5

[tabnet.initial_params.scheduler_params]
patience = 10
factor = 0.5
scheduler_fn = "torch.optim.lr_scheduler.ReduceLROnPlateau"
mode = "min"
